#!/bin/bash

localize_monitors() {
    # Replace the 'monitor' in the polybar config with the correct one for the current system.
    activemonitors=($(xrandr --listactivemonitors | awk '!/Monitor/ {print $4}'))
    primary="$(xrandr | awk '{if ($2 == "connected" && $3 == "primary") printf $1}')"
    # The next line assumes there is only 1 extra monitor
    extra="$(xrandr | awk '{if ($2 == "connected" && $3 != "primary") printf $1}')"
    for i in "${activemonitors[@]}"; do
        if [[ $i == $extra ]]; then
            secondary=$extra
            break
        fi
    done

    # Set monitor for topbar
    [[ $primary ]] && sed -E -e "s/^(topbar-monitor =).*$/\1 $primary/" -i $HOME/.config/polybar/config || \
        sed -E -e "s/^(topbar-monitor =).*$/\1/" -i $HOME/.config/polybar/config

    # Set monitor for topbar-secondary
    [[ $secondary ]] && sed -E -e "s/^(topbar-secondary-monitor =).*$/\1 $secondary/" -i $HOME/.config/polybar/config || \
        sed -E -e "s/^(topbar-secondary-monitor =).*$/\1/" -i $HOME/.config/polybar/config

    # Enable topbar-secondary when there are 2 screens
    [[ $secondary ]] && sed -E \
        -e "s/^# (polybar topbar-secondary &)/\1/" \
        -e "s/^# (ln -s.*?ipc-topbar-secondary)$/\1/" \
        -i $HOME/.local/bin/launchers/polybar_run

    # Use ramp-coreload for bigger and ramp-load for smaller monitors
    ramp=$([[ $(xrandr | awk '/primary/ {printf $4}' | cut -d x -f 1) -gt 1920 ]] && echo "ramp-coreload" || echo "ramp-load")
    sed -E -e "s/^(cpu-format =.*)<ramp-[a-z]+>(.*)$/\1<$ramp>\2/" -i $HOME/.config/polybar/config

    # Update i3 config to use secondary monitor if available
    # If there is only a primary monitor use it for all workspaces
    [[ ! $secondary ]] && secondary="$primary"
    for i in {1..10}; do
        sed -E \
            -e 's/^(workspace \$ws'"$i"' output )1$/\1'"$primary"'/' \
            -e 's/^(workspace \$ws'"$i"' output )2$/\1'"$secondary"'/' \
            -i $HOME/.config/i3/config
    done
}

localize_modules() {
    # Check modules that are available on the current system
    spotify=$([[ -f $(which spotify 2>/dev/null) ]] && echo spotify)
    mpd=$([[ -f $(which mpd 2>/dev/null) ]] && echo mpd)
    wlan=$(nmcli --fields TYPE d | grep -q wifi && echo wlan)
    battery=$([[ -f /sys/class/power_supply/ADP1/online ]] && echo battery)
    alsa=$([[ -f $(which aserver 2>/dev/null) ]] && echo alsa)
    left=" i3 xwindow"
    center=$(echo " date separator $spotify $mpd")
    right=$(echo " cpu memory $wlan eth vpn-status $battery temperature $alsa mail")
    sed -E \
        -e "s/^(topbar-modules-left =).*$/\1$left/" \
        -e "s/^(topbar-modules-center =).*$/\1$center/" \
        -e "s/^(topbar-modules-right =).*$/\1$right/" \
        -i $HOME/.config/polybar/config
    secleft=" i3 xwindow"
    seccenter=""
    secright=""
    sed -E \
        -e "s/^(topbar-secondary-modules-left =).*$/\1$secleft/" \
        -e "s/^(topbar-secondary-modules-center =).*$/\1$seccenter/" \
        -e "s/^(topbar-secondary-modules-right =).*$/\1$secright/" \
        -i $HOME/.config/polybar/config
}

localize_network() {
    # Find the correct ethernet and wlan devices to use. Only grab the first one.
    wlan=$(nmcli -g DEVICE,TYPE d | awk -F ":" '/wifi/ {print $1}' | head -n 1)
    eth=$(nmcli -g DEVICE,TYPE d | awk -F ":" '/ethernet/ {print $1}' | head -n 1)
    sed -Ee "s/^(wlan =).*$/\1 $wlan/" -e "s/^(eth =).*$/\1 $eth/" -i $HOME/.config/polybar/config
}

localize_monitors
localize_modules
localize_network
# polybar_run
