#!/usr/bin/env bash

# This updates files that are known in the repo. If files are present locally,
# but they are not part of the repo, they will be ignored.

globstar_status=$(shopt -p globstar| cut -d " " -f 2)
shopt -s globstar

cd "$(dirname $0)/dotfiles/"

update_file() {
    file=$1
    # Skip it if it's a directory
    if [[ ! -f $file ]]; then
        return 1
    fi
    if [[ ! -f $HOME/$file ]]; then
        echo "$file doesn't exist locally. Copy it (Y/n)?"
        read answer
        case $answer in
            n|N) return 1 ;;
            *) mkdir -p $(dirname $HOME/$file) && rsync -a $file $HOME/$file; return 0 ;;
        esac
    fi
    # Skip it if the files are the same
    if [[ -z $(diff -q $file $HOME/$file) ]]; then
        return 1
    fi
    echo "$file is different in repo and local install. View diff (Y/n)?"
    read answer
    case $answer in
        n|N) ;;
        *) nvim -d $file $HOME/$file ;;
    esac

}

update_files() {
    if [[ $1 == "." ]]; then
        for file in $(find $1 -maxdepth 1 -type f \! -name "..*"); do
            update_file $file
        done
    else
        for file in $1/**; do
            update_file $file
        done
        for file in $1/zsh/.*; do
            update_file $file
        done
    fi
}

# Config files
update_files .config

# Bin files
update_files .local

# Vim files
update_files .vim

# Git files
update_files .git_template

# Update files in 'root'
update_files .

# Restore previous status of globstar
shopt $globstar_status globstar
