#!/usr/bin/env sh

XF86Eject
    eject
super + ctrl + BackSpace
    sysact
super + Return
    start_terminal_in_pwd
super + space
    dmenu_run -l 10 -i
# Reload sxhkd
super + Escape
	pkill -USR1 -x sxhkd

super + b; {b,q}
    {rezblender, rezblenderqt}
super + c; {c, r, t}
    {rofi_calc, dmenu-rez-config, dmenu-term-colors toggle}
super + d; {b, c, d, e, g, f, i, m, r, t, w, x, s}
    { \
        setup-beamer, \
        colorpicker --one-shot --short --preview | tr -d '[:space:]' | xclip -selection clipboard, \
        rofi_run drun, \
        dmenu-unicode, \
        dmenu-documents, \
        feh --bg-fill $HOME/pictures/backgrounds/active_wallpaper, \
        setxinputs, \
        setup-monitors, \
        dmenu-record, \
        dmenu-record kill, \
        dmenu-window-resolution, \
        clipmenu, \
        dmenu-scrot, \
    }
super + i; {p}
    {import_photos}
super + shift + m; {m, u, s, d}
    {dmenu-mount,dmenu-umount,dmenu-servermount,dmenu-serverumount}
super + o; {b, c, g, h, m, w, p, o, j, t, y}
    { \
        toggle-bashtop, launch-chat-apps, toggle-gotop, toggle-htop, neomutt_run, $BROWSER, \
        ncmpcpp_local, ncmpcpp_guybrush, dmenu-jobs, \
        toggle-trayer, toggle-ytop \
    }
super + p
    passmenu -r -i -l 10
super + shift + p
    passmenu --username -r -i -l 10
super + ctrl + shift + p
    passmenu --otp -r -i -l 10
super + s; {p, a, s}
    {toggle-pulsemixer, play-silence, stop-silence}
super + shift + t; {c, i, r, s}
    { \
        tt-control, \
        tt-control start issue, \
        tt-control start recent, \
        tt-control stop \
    }
super + v; {m, p, j, s, u, g, w, e, h, b}
    { \
        managevpn manage, managevpn Proton-NL, managevpn jjm-studio, \
        managevpn Submarine, managevpn Proton-US, managevpn Proton-UK, \
        managewifi, wifi-off, wifi-on, \
        dmenu-bluetooth \
    }
super + w: {h, j, k, l}
    notify-send -h "string:bgcolor:#93653e" "move mode" && winmove {-50 0, 0 50, 0 -50, 50 0}
super + w: Escape
    rm $HOME/.storedwinid 2>/dev/null; pkill -ALRM sxhkd
super + shift + w: {h, j, k, l}
    notify-send -h "string:bgcolor:#93653e" "resize mode" && winresize {-100 0, 0 100, 0 -100, 100 0} centered
super + shift + w: Escape
    rm $HOME/.storedwinid 2>/dev/null; pkill -ALRM sxhkd
# Center active window (if it's floating)
super + ctrl + w:
    wincenter

# Pulse Audio controls
{_,shift} + XF86AudioRaiseVolume
    pactl set-sink-volume @DEFAULT_SINK@ +5%{;pkill -RTMIN+8 dwmblocks;, \
        ;playsound /usr/share/sounds/freedesktop/stereo/bell.oga; pkill -RTMIN+8 dwmblocks}
{_,shift} + XF86AudioLowerVolume
    pactl set-sink-volume @DEFAULT_SINK@ -5%{;pkill -RTMIN+8 dwmblocks;, \
        ;playsound /usr/share/sounds/freedesktop/stereo/bell.oga; pkill -RTMIN+8 dwmblocks}
XF86AudioMute
    pactl set-sink-mute @DEFAULT_SINK@ toggle && pkill -RTMIN+8 dwmblocks

# Sreen brightness controls
XF86MonBrightness{Up,Down}
    screen_backlight {--increase,--decrease}

# Keyboard Backlight control
XF86KbdBrightness{Up,Down}
    keyboard_backlight {--increase,--decrease}

# Media player controls
XF86AudioPlay
    playerctl play-pause || mpc toggle; pkill -RTMIN+3 dwmblocks
XF86AudioNext
    playerctl next || mpc next; pkill -RTMIN+3 dwmblocks
XF86AudioPrev
    playerctl previous || mpc prev; pkill -RTMIN+3 dwmblocks

# vim: set ts=4 sw=4 tw=72 et:
