#!/usr/bin/env sh

XF86Eject
    eject
super + ctrl + BackSpace
    sysact
super + Return
    start_terminal_in_pwd
super + space
    rofi_run
# Reload sxhkd
super + Escape
	pkill -USR1 -x sxhkd
# super + equal
#     i3-msg -q "[class=alacritty title=scratchpad]" scratchpad show

super + b; {b,q}
    {rezblender, rezblenderqt}
super + c; {c,r}
    {rofi_calc, dmenu-rez-config}
super + d; {b, d, e, g, f, i, m, p, x, s}
    { \
        i3-msg -q "border toggle 4", \
        rofi_run drun, \
        dmenu-unicode, \
        dmenu-documents, \
        feh --bg-fill $HOME/pictures/backgrounds/active_wallpaper, \
        setxinputs, \
        setup-monitors, \
        start_pomodoro, \
        clipmenu, \
        dmenu-scrot, \
    }
# super + w; {b,p,m,i,s}
#     {i3-msg -q "border toggle 4",start_pomodoro,setup-monitors,setxinputs,polybar_run}
super + w: {h, j, k, l}
    notify-send -h "string:bgcolor:#93653e" "move mode" && winmove {-50 0, 0 50, 0 -50, 50 0}
super + w: Escape
    rm $HOME/.storedwinid 2>/dev/null; pkill -ALRM sxhkd
super + shift + w: {h, j, k, l}
    notify-send -h "string:bgcolor:#93653e" "resize mode" && winresize {-100 0, 0 100, 0 -100, 100 0} centered
super + shift + w: Escape
    rm $HOME/.storedwinid 2>/dev/null; pkill -ALRM sxhkd
super + i; {p,s}
    {import_photos,top_run}
super + shift + m; {m,u,s,d}
    {dmenu-mount,dmenu-umount,dmenu-servermount,dmenu-serverumount}
super + o; {b, c, h, m, w, e, s, p, o, j, t}
    { \
        toggle-bashtop, dmenu-term-colors, toggle-htop, neomutt_run, $BROWSER, \
        emacs, emacs, ncmpcpp_local, ncmpcpp_guybrush, dmenu-jobs, \
        toggle-trayer
    }
super + p
    passmenu
super + s; {a, b, p}
    { \
        i3-msg -q "[class=cli.py title=(?im)^.*|\s+allzpark\s+.*$] scratchpad show", \
        i3-msg -q "[class=alacritty title=blender*] scratchpad show", \
        toggle-pulsemixer \
        # i3-msg -q "[class=alacritty title=scratchpad] scratchpad show", \
    }
super + v; {m, p, j, s, u, g, w, e, h, b}
    { \
        managevpn manage, managevpn Proton-NL, managevpn jjm-studio, \
        managevpn Submarine, managevpn Proton-US, managevpn Proton-UK, \
        managewifi, wifi-off, wifi-on, \
        dmenu-bluetooth \
    }
# super + shift + w
#     rename_workspace
# super + x; {x, s}
#     {clipmenu, dmenu-scrot}

# Pulse Audio controls
{_,shift} + XF86AudioRaiseVolume
    pactl set-sink-volume @DEFAULT_SINK@ +5%{;pkill -RTMIN+8 dwmblocks;, \
        ;playsound /usr/share/sounds/freedesktop/stereo/bell.oga; pkill -RTMIN+8 dwmblocks}
{_,shift} + XF86AudioLowerVolume
    pactl set-sink-volume @DEFAULT_SINK@ -5%{;pkill -RTMIN+8 dwmblocks;, \
        ;playsound /usr/share/sounds/freedesktop/stereo/bell.oga; pkill -RTMIN+8 dwmblocks}
XF86AudioMute
    pactl set-sink-mute @DEFAULT_SINK@ toggle && pkill -RTMIN+8 dwmblocks

# Sreen brightness controls
XF86MonBrightness{Up,Down}
    screen_backlight {--increase,--decrease}

# Keyboard Backlight control
XF86KbdBrightness{Up,Down}
    keyboard_backlight {--increase,--decrease}

# Media player controls
XF86AudioPlay
    playerctl play-pause || mpc toggle; pkill -RTMIN+3 dwmblocks
XF86AudioNext
    playerctl next || mpc next; pkill -RTMIN+3 dwmblocks
XF86AudioPrev
    playerctl previous || mpc prev; pkill -RTMIN+3 dwmblocks

# vim: set ts=4 sw=4 tw=72 et:
