#!/usr/bin/env sh

XF86Eject
    eject
super + ctrl + BackSpace
    sysact
super + Return
    start_terminal_in_pwd
super + space
    rofi -show combi -modes combi -combi-modes drun,run
# Reload sxhkd
super + Escape
	pkill -USR1 -x sxhkd

super + b; {b,q}
    {rezblender, rezblenderqt}
super + c; {c, r, t}
    {rofi_calc, dmenu-rez-config, dmenu-term-colors toggle}
super + d; {b, c, d, e, g, f, i, m, r, t, w, x, s}
    { \
        setup-beamer 1280x720, \
        colorpicker --one-shot --short --preview | tr -d '[:space:]' | xclip -selection clipboard, \
        rofi_run drun, \
        dmenu-unicode, \
        dmenu-documents, \
        feh --bg-fill $HOME/pictures/backgrounds/active_wallpaper, \
        setxinputs, \
        setup-monitors auto, \
        dmenu-record, \
        dmenu-record kill, \
        dmenu-window-resolution, \
        clipmenu, \
        dmenu-scrot, \
    }
super + shift + d; {m}
    {setup-monitors}
super + ctrl + d; {m}
    {setup-monitors-knmi}
super + ctrl + l;
    jasperge-locker --force
super + i; {p}
    {media-import}
super + n; {m, p, j, s, u, g, w, e, h, b}
    { \
        managevpn manage, managevpn Proton-NL, managevpn jjm-studio, \
        managevpn Submarine, managevpn Proton-US, managevpn Proton-UK, \
        managewifi, wifi-off, wifi-on, \
        dmenu-bluetooth \
    }
super + shift + m; {m, u, s, d}
    {dmenu-mount,dmenu-umount,dmenu-servermount,dmenu-serverumount}
super + o; {b, c, f, g, h, m, w, i, p, o, u, s, t, y, n, z}
    { \
        toggle-btop, launch-chat-apps, toggle-weather, toggle-gotop, toggle-htop\
        , mailclient , $BROWSER, player-switch, ncmpcpp_local, ncmpcpp_guybrush \
        , spotify-tui, toggle-touchscreen, toggle-trayer \
        , toggle-ytop, toggle-nethogs, upgrade-os-term \
    }
super + p
    passmenu -r -i -l 10
super + shift + p
    passmenu --username -r -i -l 10
super + ctrl + shift + p
    passmenu --otp -r -i -l 10
super + s; {p, a, s}
    {toggle-pulsemixer, play-silence, stop-silence}
super + ctrl + t; {k, s}
    {tmux-kill-session, tmux-start-session}
super + shift + t; {r, s}
    { \
        tt-control start recent, \
        tt-control stop \
    }
# super + shift + t; {c, i, a, r, s}
#     { \
#         tt-control, \
#         tt-control start issue, \
#         tt-control start issue-all, \
#         tt-control start recent, \
#         tt-control stop \
#     }
# 'special' vim 'windows'
super + v; {w}
    {vimwiki-term}
super + w: {h, j, k, l}
    notify-send -h "string:bgcolor:#93653e" "move mode" && winmove {-50 0, 0 50, 0 -50, 50 0}
super + w: Escape
    rm $HOME/.storedwinid 2>/dev/null; pkill -ALRM sxhkd
super + shift + w: {h, j, k, l}
    notify-send -h "string:bgcolor:#93653e" "resize mode" && winresize {-100 0, 0 100, 0 -100, 100 0} centered
super + shift + w: Escape
    rm $HOME/.storedwinid 2>/dev/null; pkill -ALRM sxhkd
# Center active window (if it's floating)
super + ctrl + w:
    wincenter

# Dunst notifications
super + shift + d; {a, c, h, x}
    {dunstctl close-all, dunstctl close, dunstctl history-pop, dunstctl context}

# Kill windows
super + shift + x:
    xkill

# Pulse Audio controls
{_,shift} + XF86AudioRaiseVolume
    wpctl set-volume @DEFAULT_SINK@ 0.05+{;pkill -RTMIN+8 dwmblocks;, \
        ;ffplay -nodisp -autoexit /usr/share/sounds/freedesktop/stereo/bell.oga; pkill -RTMIN+8 dwmblocks}
{_,shift} + XF86AudioLowerVolume
    wpctl set-volume @DEFAULT_SINK@ 0.05-{;pkill -RTMIN+8 dwmblocks;, \
        ;ffplay -nodisp -autoexit /usr/share/sounds/freedesktop/stereo/bell.oga; pkill -RTMIN+8 dwmblocks}
XF86AudioMute
    wpctl set-mute @DEFAULT_SINK@ toggle && pkill -RTMIN+8 dwmblocks

# Sreen brightness controls
XF86MonBrightness{Up,Down}
    screen_backlight {--increase,--decrease}

# Keyboard Backlight control
XF86KbdBrightness{Up,Down}
    keyboard_backlight {--increase,--decrease}

# Media player controls
XF86AudioPlay
    playerctl -a play-pause || mpc toggle; pkill -RTMIN+3 dwmblocks
XF86AudioNext
    playerctl -a next || mpc next; pkill -RTMIN+3 dwmblocks
XF86AudioPrev
    playerctl -a previous || mpc prev; pkill -RTMIN+3 dwmblocks

# vim: set ts=4 sw=4 tw=72 et:
